### ISSUE TITLE
Couple of questions for bindings

### ISSUE THREAD

**Issue by ticktricktrack** [maartentamboer/X-Touch-Mini-FS2020#1]
Hi, I found your xtouch project while googling. I'm going to assume it's all python3, correct? 

- `alternate_event_up` - is that the layer B?
- not sure what a trigger is
- do you have the slider/fader working as well? Not sure that's even doable through simconnect.
  - I wonder if it could be mapped to https://github.com/odwdinc/Python-SimConnect/blob/master/SimConnect/EventList.py#L103

**Comment by maartentamboer** [comment]
> alternate_event_up - is that the layer B?

To use layer b just continue numbering up the indexes. So encoder with index 9 should be the first encoder on layer B.
There are some challenges with the LED feedback, because the x-touch does not send a message when you switch layers. I only see it when you press a button/ rotate an encoder. that's the reason for activelayer.py.

> not sure what a trigger is

Regarding alternate event up and triggers, I'll explain how encoder 5 and encoder 6 works in my config file.
Encoder 5 by default controls the SPD parameter of the autopilot (generally used for FLC), but when the AUTOPILOT_VERTICAL_HOLD is activated (VS) it switches automatically to control vertical speed. Basically AUTOPILOT_VERTICAL_HOLD triggers encoder 5 to alternate mode.

Encoder 6 controls the nav frequency, first it controls the whole digits, when you press the encoder it switches to the fractional digits and when you long press it swaps the frequency.

> do you have the slider/fader working as well?

Not yet, but I should be able to add that fairly easily. And then it can be mapped to any of the simevents that require a value

**Comment by maartentamboer** [comment]
> I'm going to assume it's all python3, correct?
Yes, that's correct

**Comment by ticktricktrack** [comment]
Thank you, I'll give it a got later.

**Comment by maartentamboer** [comment]
Just added support for the fader, it's in the main branch.
Also added some details about the encoder configuration through the x-touch editor, which is important to do. Otherwise the software will behave very strange

**Comment by ticktricktrack** [comment]
Wow that was quick, I'll fork the repo and send a readme PR back. I've only used python on Mac and Linux so far, I'll make note of the steps.

**Comment by ticktricktrack** [comment]
Thanks, that worked quite well. Biggest hurdle was windows actually. (images for github hosting, see PR)

![X-TOUCH-MINI_P0B3M_Top_XL](https://user-images.githubusercontent.com/82336/96199071-7e8d7e80-0f4e-11eb-97e7-30d4527aa112.png)
![xtouch_editor](https://user-images.githubusercontent.com/82336/96199074-7fbeab80-0f4e-11eb-9bb6-bf8b912a0fb2.png)

**Comment by ticktricktrack** [comment]
![python_path](https://user-images.githubusercontent.com/82336/96336775-1045da80-107a-11eb-8b4e-bd80fd6b170d.png)
