### ISSUE TITLE
Empty triggers cause fail

### ISSUE THREAD

**Issue by themazen** [maartentamboer/X-Touch-Mini-FS2020#18]
When the triggers in the configuration file are empty, it breaks line 76 of main.py.

**Comment by maartentamboer** [comment]
Can you show your config file? 
The following code should work
```json
"triggers": [ ]
```

See also https://github.com/maartentamboer/X-Touch-Mini-FS2020/issues/16

**Comment by themazen** [comment]
Sure, I also tried to completely remove the triggers object and got an error for another line.

With **"triggers": [ ]**
![image](https://user-images.githubusercontent.com/77670950/106354665-c95fb600-62f3-11eb-996b-6af1cac74518.png)

With triggers object completely removed  :
![image](https://user-images.githubusercontent.com/77670950/106354675-d5e40e80-62f3-11eb-8331-ac1acf302edd.png)

[config_default.json.txt](https://github.com/maartentamboer/X-Touch-Mini-FS2020/files/5897809/config_default.json.txt)

**Comment by maartentamboer** [comment]
https://github.com/maartentamboer/X-Touch-Mini-FS2020/blob/main/main.py#L76

This line is causing that, that is clearly something that shouldn't be there. Probably left over from testing. Looking at it in more detail it appears that separate triggers are broken entirely since my changes in https://github.com/maartentamboer/X-Touch-Mini-FS2020/pull/7 

Will create a quick patch release to remove that line

**Comment by maartentamboer** [comment]
Release 1.0.1 is now available which should work when you do `"triggers": [ ]`
https://github.com/maartentamboer/X-Touch-Mini-FS2020/releases/tag/v1.0.1
